### ISSUE TITLE
plz update readme

### ISSUE THREAD

**Issue by timoxley** [qualiancy/seed#1]
This package sounds good, can you please update the readme?

**Comment by logicalparadox** [comment]
Sure thing. First non-patch release (0.1.0) will be in a few days. Will include in there.

**Comment by logicalparadox** [comment]
I put the basics into the readme. Should be enough to give an idea of the project goals. The API isn't quite stable yet but will be with the 0.1.0 release. I will have an API guide then. Let me know what you think.

Cheers.

**Comment by timoxley** [comment]
Awesome, thanks. 1602 is doing something kind of similar: https://github.com/1602/jugglingdb . Perhaps you could steal some of his db adaptors ;)

**Comment by logicalparadox** [comment]
Looks interesting. I'll keep an eye on it. Let me know if you use Seed or have feature requests. For instance, do you have a db of choice? I was planning to do mongo, couch, redis ... in that order as I need them but willing to shuffle around a bit.

Cheers.

**Comment by timoxley** [comment]
Currently using Mongo+Redis. Hope to try seed out in coming weeks. What are you using seed for personally?
