### ISSUE TITLE
Extract schema out of seed

### ISSUE THREAD

**Issue by vesln** [qualiancy/seed#12]
I'd like to use `Schema` independently so I can cast and normalize user input. Would this be a good idea?

**Comment by logicalparadox** [comment]
Yes! I (have || will be) extracting all of the "submodules" into separate repos. 

Schema is one that I have already extracted: https://github.com/qualiancy/gaia-schema
Note: the API is a bit different.

Sorry, no docs but... examples:
- validate/cast custom functions: [here](https://github.com/qualiancy/carbon/blob/refactor/node10/lib/carbon/balancer/schema.js)
- usage for cast: [here](https://github.com/qualiancy/carbon/blob/refactor/node10/lib/carbon/balancer/proto/_base.state.js#L53-L62)

I'm currently 2 days deep in a big rewrite to seed. Not sure yet where everything is going to end up but will let you know when and how to migrate to the new version.
