### ISSUE TITLE
Support for generator based flow-control 

### ISSUE THREAD

**Issue by vesln** [qualiancy/seed#13]
Just a feature request for seed next. I'm seeing it is already using promises so it should be pretty straight forward.

**Comment by logicalparadox** [comment]
Already on the list... also, it is using an old version of `oath` which was promised based. Nobody used it (including myself except for seed legacy) so I rewrote it as a thunk utility...

see: https://github.com/logicalparadox/oath
example: https://github.com/logicalparadox/comm/blob/11cdce98fd254189890a1dcd2b6b1acc6b3bafa3/lib/chan.js#L89-L110

**Comment by vesln** [comment]
I'm not really familiar with thunks but as soon as seed's api can support both callbacks and generators I'd be very satisfied

**Comment by logicalparadox** [comment]
i have been debating with myself as to whether i should use `co` and generators internally in seed.next. On one hand it would make the code awesomely simple, but it would limit the environments it can run in. Only modern node, no browser (for the time being). 

Thoughts?

**Comment by vesln** [comment]
I personally don't care much about the browser so if using co will improve everything _significantly_ - it's worth, otherwise I wouldn't take this path and probably stick with the promises since co supports them, `q` works everywhere and there is very little effort required to support fibers, generators, promises and simple callbacks. Take a look at [wd](https://github.com/admc/wd/) for inspiration.
